name: Process Bot

on:
  issue_comment:
    types: [created]

permissions: write-all

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  process:
    name: Process Comment
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/bot ') }}
    runs-on: ubuntu-latest
    steps:
      - uses: xlc/fellowship-process-bot@main
